{
  "packages":
    [
      "crates/tsc/js",
      "packages/playground",
      "packages/wasm",
      "packages/wasm/test",
    ],
  "catalog":
    {
      "@codemirror/lang-javascript": "^6.2.2",
      "@sveltejs/vite-plugin-svelte": "^5.0.3",
      "@tsconfig/svelte": "^5.0.4",
      "svelte": "^5.15.0",
      "svelte-check": "^4.1.1",
      "svelte-codemirror-editor": "^1.4.1",
      "typescript": "~5.6.2",
      "vite": "^6.0.5",
      "zx": "^8.3.0",
    },
}
