packages:
  - crates/tsc/js
  - crates/bench
  - packages/playground
  - packages/wasm
  - packages/wasm/test
catalog:
  "@codemirror/lang-javascript": ^6.2.2
  "@sveltejs/vite-plugin-svelte": ^5.0.3
  "@ts-morph/bootstrap": ^0.26.0
  "@tsconfig/svelte": ^5.0.4
  "@types/node": ^22.10.9
  codemirror: ^6.0.1
  esbuild: ^0.24.2
  markdown-table: ^3.0.4
  svelte: ^5.15.0
  svelte-check: ^4.1.1
  svelte-codemirror-editor: ^1.4.1
  tsx: ^4.19.2
  typescript: ~5.6.2
  vite: ^6.0.5
  vite-plugin-wasm: ^3.4.1
  zx: ^8.3.0
