[package]
name = "oxidase_e2e"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
oxidase = { workspace = true }
pretty_assertions = { workspace = true }
ignore = "0.4.23"
oxidase_tsc = { workspace = true }
rayon.workspace = true
similar-asserts = "1.6.0"
