[package]
name = "oxidase_wasm_bindings"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
oxidase = { workspace = true }
serde = { workspace = true, features = [ "derive" ]}
# talc = { version = "4.4.2", default-features = false, features = ["lock_api"]}

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
