[package]
name = "oxidase_wasm_bindings"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
console_error_panic_hook = "0.1.7"
oxidase = { workspace = true }
serde = { workspace = true, features = [ "derive" ]}
# talc = { version = "4.4.2", default-features = false, features = ["lock_api"]}

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
