name: Compare

on:
  workflow_dispatch:

jobs:
  compare:
    name: Compare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup show
      - uses: jdx/mise-action@v2
      - run: pnpm install
      - run: mise run compare:time
      - run: mise run compare:memory
