name: Compare

on:
  workflow_dispatch:

jobs:
  compare-time:
    strategy:
      matrix:
        include:
          - name: Linux x64
            os: ubuntu-24.04
          - name: Linux arm64
            os: ubuntu-24.04-arm
          - name: macOS x64
            os: macos-13
          - name: macOS arm64
            os: macos-14
    name: Compare Time (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup show
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required to prevent rate limiting of GitHub requests raised by cargo binstall
      - run: pnpm install
      - run: mise run compare:time --no-run
      - run: mise run compare:time
  compare-memory:
    name: Compare Memory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup show
      - uses: jdx/mise-action@v2
      - run: pnpm install
      - run: mise run compare:memory --no-run
      - run: mise run compare:memory
